version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  Build-Deploy:

    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: install dependencies Frontend
          command: |
            npm run frontend:install
      - run:
          name: install dependencies Backend
          command: |
            npm run backend:install
      - run:
          name: Build Frontend
          command: |
            npm run frontend:build
      - run:
          name: Build Backend
          command: |
            npm run backend:build
      - run:
          name: Deploy Frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Back-End
          command: |
            npm run backend:deploy

workflows:
  deployment:
    jobs:
    # Build & Deploy project on Main Branch
      - Build-Deploy:
         filters:
            branches:
              only: main